### PR TITLE
Version bump to 0.10.1 (updated bl package)

### PR DESCRIPTION
**Pull request by rvravi**
Bumping the patch version to 0.10.1 from 0.10.0. 
Doing this to release a new version so that we can adopt the changes which contain the security fix.

### CODE REVIEW

**Comment by rvravi** [comment]
Hi @mikeal It will be great if you can merge this PR and publish the package

**Comment by hemanthreddyk** [comment]
@mikeal  Can you please merge this PR and release a new npm version so that we can consume it. Thanks in advance.

**Comment by rvravi** [comment]
@mikeal @jcrugzz Any chance for this to get merged asap?

**Comment by mikeal** [comment]
released 0.11.0 with my local release script.

sorry that this takes so long, most of my packages have automated releases so don’t notice when things aren’t automatically released.

i’m not really maintaining this project anymore, if other people are interested in maintaining it i can add you as contributors.

**Pull request closed without merging**
